# Generated by Django 5.2.7 on 2026-04-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Development', 'Development'), ('Marketing', 'Marketing'), ('Design', 'Design')], max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='courses/')),
                ('progress', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20)),
            ],
        ),
    ]
